import GlobalState from '@/context'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DirectDeal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState className="text-black">
          <Navbar/>
          <main className='flex min-h-screen flex-col mt-[80px] text-black'>{children}</main>
        </GlobalState>
      </body>
    </html>
  )
}
